using System;

namespace ArcanumFileFormats.ObjectsNew.Flags
{
	[Flags]
	public enum obj_f_spell_flags_
	{
		OSF_INVISIBLE = 1,
		OSF_FLOATING,
		OSF_BODY_OF_AIR,
		OSF_BODY_OF_EARTH,
		OSF_BODY_OF_FIRE,
		OSF_BODY_OF_WATER,
		OSF_DETECTING_MAGIC,
		OSF_DETECTING_ALIGNMENT,
		OSF_DETECTING_TRAPS,
		OSF_DETECTING_INVISIBLE,
		OSF_SHIELDED,
		OSF_ANTI_MAGIC_SHELL,
		OSF_BONDS_OF_MAGIC,
		OSF_FULL_REFLECTION,
		OSF_SUMMONED,
		OSF_ILLUSION,
		OSF_STONED,
		OSF_POLYMORPHED,
		OSF_MIRRORED,
		OSF_SHRUNK,
		OSF_PASSWALLED,
		OSF_WATER_WALKING,
		OSF_MAGNETIC_INVERSION,
		OSF_CHARMED,
		OSF_ENTANGLED,
		OSF_SPOKEN_WITH_DEAD,
		OSF_TEMPUS_FUGIT,
		OSF_MIND_CONTROLLED,
		OSF_DRUNK,
		OSF_ENSHROUDED,
		OSF_FAMILIAR,
		OSF_HARDENED_HANDS
	}
}

