using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;

namespace ArcanumFileFormats.ObjectsNew.Legacy
{
    public enum ObjectField : int
    {
        obj_f_current_aid = 0,
        obj_f_location = 1,
        obj_f_offset_x = 2,
        obj_f_offset_y = 3,
        obj_f_shadow = 4,
        obj_f_overlay_fore = 5,
        obj_f_overlay_back = 6,
        obj_f_underlay = 7,
        obj_f_blit_flags = 8,
        obj_f_blit_color = 9,
        obj_f_blit_alpha = 10,
        obj_f_blit_scale = 11,
        obj_f_light_flags = 12,
        obj_f_light_aid = 13,
        obj_f_light_color = 14,
        obj_f_overlay_light_flags = 15,
        obj_f_overlay_light_aid = 16,
        obj_f_overlay_light_color = 17,
        obj_f_flags = 18,
        obj_f_spell_flags = 19,
        obj_f_blocking_mask = 20,
        obj_f_name = 21,
        obj_f_description = 22,
        obj_f_aid = 23,
        obj_f_destroyed_aid = 24,
        obj_f_AC = 25,
        obj_f_hp_pts = 26,
        obj_f_hp_adj = 27,
        obj_f_hp_damage = 28,
        obj_f_material = 29,
        obj_f_resistance_idx = 30,
        obj_f_scripts_idx = 31,
        obj_f_sound_effect = 32,
        obj_f_category = 33,
        obj_f_pad_ias_1 = 34,
        obj_f_pad_i64as_1 = 35,
        obj_f_wall_flags = 64,
        obj_f_wall_pad_i_1 = 65,
        obj_f_wall_pad_i_2 = 66,
        obj_f_wall_pad_ias_1 = 67,
        obj_f_wall_pad_i64as_1 = 68,

        obj_f_portal_flags = 64,
        obj_f_portal_lock_difficulty = 65,
        obj_f_portal_key_id = 66,
        obj_f_portal_notify_npc = 67,
        obj_f_portal_pad_i_1 = 68,
        obj_f_portal_pad_i_2 = 69,
        obj_f_portal_pad_ias_1 = 70,
        obj_f_portal_pad_i64as_1 = 71,

        obj_f_container_flags = 64,
        obj_f_container_lock_difficulty = 65,
        obj_f_container_key_id = 66,
        obj_f_container_inventory_num = 67,
        obj_f_container_inventory_list_idx = 68,
        obj_f_container_inventory_source = 69,
        obj_f_container_notify_npc = 70,
        obj_f_container_pad_i_1 = 71,
        obj_f_container_pad_i_2 = 72,
        obj_f_container_pad_ias_1 = 73,
        obj_f_container_pad_i64as_1 = 74,

        obj_f_scenery_flags = 64,
        obj_f_scenery_whos_in_me = 65,
        obj_f_scenery_respawn_delay = 66,
        obj_f_scenery_pad_i_2 = 67,
        obj_f_scenery_pad_ias_1 = 68,
        obj_f_scenery_pad_i64as_1 = 69,

        obj_f_projectile_flags_combat = 0,
        obj_f_projectile_flags_combat_damage = 1,
        obj_f_projectile_hit_loc = 2,
        obj_f_projectile_parent_weapon = 3,
        obj_f_projectile_pad_i_1 = 4,
        obj_f_projectile_pad_i_2 = 5,
        obj_f_projectile_pad_ias_1 = 6,
        obj_f_projectile_pad_i64as_1 = 7,

        obj_f_item_flags = 64,
        obj_f_item_parent = 65,
        obj_f_item_weight = 66,
        obj_f_item_magic_weight_adj = 67,
        obj_f_item_worth = 68,
        obj_f_item_mana_store = 69,
        obj_f_item_inv_aid = 70,
        obj_f_item_inv_location = 71,
        obj_f_item_use_aid_fragment = 72,
        obj_f_item_magic_tech_complexity = 73,
        obj_f_item_discipline = 74,
        obj_f_item_description_unknown = 75,
        obj_f_item_description_effects = 76,
        obj_f_item_spell_1 = 77,
        obj_f_item_spell_2 = 78,
        obj_f_item_spell_3 = 79,
        obj_f_item_spell_4 = 80,
        obj_f_item_spell_5 = 81,
        obj_f_item_spell_mana_store = 82,
        obj_f_item_ai_action = 83,
        obj_f_item_pad_i_1 = 84,
        obj_f_item_pad_ias_1 = 85,
        obj_f_item_pad_i64as_1 = 86,

        obj_f_weapon_flags = 96,
        obj_f_weapon_paper_doll_aid = 97,
        obj_f_weapon_bonus_to_hit = 98,
        obj_f_weapon_magic_hit_adj = 99,
        obj_f_weapon_damage_lower_idx = 100,
        obj_f_weapon_damage_upper_idx = 101,
        obj_f_weapon_magic_damage_adj_idx = 102,
        obj_f_weapon_speed_factor = 103,
        obj_f_weapon_magic_speed_adj = 104,
        obj_f_weapon_range = 105,
        obj_f_weapon_magic_range_adj = 106,
        obj_f_weapon_min_strength = 107,
        obj_f_weapon_magic_min_strength_adj = 108,
        obj_f_weapon_ammo_type = 109,
        obj_f_weapon_ammo_consumption = 110,
        obj_f_weapon_missile_aid = 111,
        obj_f_weapon_visual_effect_aid = 112,
        obj_f_weapon_crit_hit_chart = 113,
        obj_f_weapon_magic_crit_hit_chance = 114,
        obj_f_weapon_magic_crit_hit_effect = 115,
        obj_f_weapon_crit_miss_chart = 116,
        obj_f_weapon_magic_crit_miss_chance = 117,
        obj_f_weapon_magic_crit_miss_effect = 118,

        obj_f_weapon_pad_i_1 = 119,
        obj_f_weapon_pad_i_2 = 120,
        obj_f_weapon_pad_ias_1 = 121,
        obj_f_weapon_pad_i64as_1 = 122,

        obj_f_ammo_flags = 96,
        obj_f_ammo_quantity = 97,
        obj_f_ammo_type = 98,
        obj_f_ammo_pad_i_1 = 99,
        obj_f_ammo_pad_i_2 = 100,
        obj_f_ammo_pad_ias_1 = 101,
        obj_f_ammo_pad_i64as_1 = 102,

        obj_f_armor_flags = 96,
        obj_f_armor_paper_doll_aid = 97,
        obj_f_armor_ac_adj = 98,
        obj_f_armor_magic_ac_adj = 99,
        obj_f_armor_resistance_adj_idx = 100,
        obj_f_armor_magic_resistance_adj_idx = 101,
        obj_f_armor_silent_move_adj = 102,
        obj_f_armor_magic_silent_move_adj = 103,
        obj_f_armor_unarmed_bonus_damage = 104,
        obj_f_armor_pad_i_2 = 105,
        obj_f_armor_pad_ias_1 = 106,
        obj_f_armor_pad_i64as_1 = 107,

        obj_f_gold_flags = 96,
        obj_f_gold_quantity = 97,
        obj_f_gold_pad_i_1 = 98,
        obj_f_gold_pad_i_2 = 99,
        obj_f_gold_pad_ias_1 = 100,
        obj_f_gold_pad_i64as_1 = 101,

        obj_f_food_flags = 96,
        obj_f_food_pad_i_1 = 97,
        obj_f_food_pad_i_2 = 98,
        obj_f_food_pad_ias_1 = 99,
        obj_f_food_pad_i64as_1 = 100,

        obj_f_scroll_flags = 96,
        obj_f_scroll_pad_i_1 = 97,
        obj_f_scroll_pad_i_2 = 98,
        obj_f_scroll_pad_ias_1 = 99,
        obj_f_scroll_pad_i64as_1 = 100,

        obj_f_key_key_id = 96,
        obj_f_key_pad_i_1 = 97,
        obj_f_key_pad_i_2 = 98,
        obj_f_key_pad_ias_1 = 99,
        obj_f_key_pad_i64as_1 = 100,
        obj_f_key_ring_flags = 96,
        obj_f_key_ring_list_idx = 97,
        obj_f_key_ring_pad_i_1 = 98,
        obj_f_key_ring_pad_i_2 = 99,
        obj_f_key_ring_pad_ias_1 = 100,
        obj_f_key_ring_pad_i64as_1 = 101,

        obj_f_written_flags = 96,
        obj_f_written_subtype = 97,
        obj_f_written_text_start_line = 98,
        obj_f_written_text_end_line = 99,
        obj_f_written_pad_i_1 = 100,
        obj_f_written_pad_i_2 = 101,
        obj_f_written_pad_ias_1 = 102,
        obj_f_written_pad_i64as_1 = 103,

        obj_f_generic_flags = 96,
        obj_f_generic_usage_bonus = 97,
        obj_f_generic_usage_count_remaining = 98,
        obj_f_generic_pad_ias_1 = 99,
        obj_f_generic_pad_i64as_1 = 100,

        obj_f_critter_flags = 64,
        obj_f_critter_flags2 = 65,
        obj_f_critter_stat_base_idx = 66,
        obj_f_critter_basic_skill_idx = 67,
        obj_f_critter_tech_skill_idx = 68,
        obj_f_critter_spell_tech_idx = 69,
        obj_f_critter_fatigue_pts = 70,
        obj_f_critter_fatigue_adj = 71,
        obj_f_critter_fatigue_damage = 72,
        obj_f_critter_crit_hit_chart = 73,
        obj_f_critter_effects_idx = 74,
        obj_f_critter_effect_cause_idx = 75,
        obj_f_critter_fleeing_from = 76,
        obj_f_critter_portrait = 77,
        obj_f_critter_gold = 78,
        obj_f_critter_arrows = 79,
        obj_f_critter_bullets = 80,
        obj_f_critter_power_cells = 81,
        obj_f_critter_fuel = 82,
        obj_f_critter_inventory_num = 83,
        obj_f_critter_inventory_list_idx = 84,
        obj_f_critter_inventory_source = 85,
        obj_f_critter_description_unknown = 86,
        obj_f_critter_follower_idx = 87,
        obj_f_critter_teleport_dest = 88,
        obj_f_critter_teleport_map = 89,
        obj_f_critter_death_time = 90,
        obj_f_critter_auto_level_scheme = 91,
        obj_f_critter_pad_i_1 = 92,
        obj_f_critter_pad_i_2 = 93,
        obj_f_critter_pad_i_3 = 94,
        obj_f_critter_pad_ias_1 = 95,
        obj_f_critter_pad_i64as_1 = 96,

        obj_f_pc_flags = 128,
        obj_f_pc_flags_fate = 129,
        obj_f_pc_reputation_idx = 130,
        obj_f_pc_reputation_ts_idx = 131,
        obj_f_pc_background = 132,
        obj_f_pc_background_text = 133,
        obj_f_pc_quest_idx = 134,
        obj_f_pc_blessing_idx = 134,
        obj_f_pc_blessing_ts_idx = 135,
        obj_f_pc_curse_idx = 136,
        obj_f_pc_curse_ts_idx = 137,
        obj_f_pc_party_id = 138,
        obj_f_pc_rumor_idx = 139,
        obj_f_pc_pad_ias_2 = 140,
        obj_f_pc_schematics_found_idx = 141,
        obj_f_pc_logbook_ego_idx = 142,
        obj_f_pc_fog_mask = 143,
        obj_f_pc_player_name = 144,
        obj_f_pc_bank_money = 145,
        obj_f_pc_global_flags = 146,
        obj_f_pc_global_variables = 147,
        obj_f_pc_pad_i_1 = 148,
        obj_f_pc_pad_i_2 = 149,
        obj_f_pc_pad_ias_1 = 150,
        obj_f_pc_pad_i64as_1 = 151,
        obj_f_pc_pad_i64as_2 = 152,

        obj_f_npc_flags = 128,
        obj_f_npc_leader = 129,
        obj_f_npc_ai_data = 130,
        obj_f_npc_combat_focus = 131,
        obj_f_npc_who_hit_me_last = 132,
        obj_f_npc_experience_worth = 133,
        obj_f_npc_experience_pool = 134,
        obj_f_npc_waypoints_idx = 135,
        obj_f_npc_waypoint_current = 136,
        obj_f_npc_standpoint_day = 137,
        obj_f_npc_standpoint_night = 138,
        obj_f_npc_origin = 139,
        obj_f_npc_faction = 140,
        obj_f_npc_retail_price_multiplier = 141,
        obj_f_npc_substitute_inventory = 142,
        obj_f_npc_reaction_base = 143,
        obj_f_npc_social_class = 144,
        obj_f_npc_reaction_pc_idx = 145,
        obj_f_npc_reaction_level_idx = 146,
        obj_f_npc_reaction_time_idx = 147,
        obj_f_npc_wait = 148,
        obj_f_npc_generator_data = 149,
        obj_f_npc_pad_i_1 = 150,
        obj_f_npc_damage_idx = 151,
        obj_f_npc_shit_list_idx = 152,

        obj_f_trap_flags = 64,
        obj_f_trap_difficulty = 65,
        obj_f_trap_pad_i_2 = 66,
        obj_f_trap_pad_ias_1 = 67,
        obj_f_trap_pad_i64as_1 = 68
    }
}
